# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-27 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128)),
                ('taste', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
    ]
