# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('hero', models.CharField(max_length=30)),
                ('actress', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
